apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sagar-frontend
  template:
    metadata:
      labels:
        app: sagar-frontend
    spec:
      containers:
      - name: sagar-frontend
        image: docker.io/sagar0547/tutedude_ass5_frontend
        ports:
        - containerPort: 4000
        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000/register"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: sagar-frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000