version: '3.8'

services:
  backend:
    build: ./backend
    hostname: backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - my_network

  frontend:
    build: ./frontend
    hostname: frontend
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:5000/register
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge